<a href="https://colab.research.google.com/github/Glaze0/Assignment/blob/main/Workshop_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 print("Hello dosto!")

Hello dosto!

#Classification vs Regression

In [ ]:
# Classification                    Regression

# - Predicting the category         - Predicting a continuous value
# - Spam/Not spam                   - House Price Prediction

In [ ]:
import pandas as pd

df = pd.DataFrame({

    "Area":[
        800,900,950,1000,1100,
        1200,1300,1400,1500,1600,
        1700,1800,1900,2000,2100,
        2200,2300,2400,2500,2600
    ],

    "Bedrooms":[
        2,2,2,2,2,
        3,3,3,3,3,
        3,3,4,4,4,
        4,4,4,5,5
    ],

    "Age":[
        18,15,14,13,12,
        11,10,9,8,8,
        7,6,5,5,4,
        4,3,3,2,1
    ],

    "Price":[
        38,43,46,50,55,
        61,67,73,79,84,
        89,95,103,110,116,
        122,128,134,142,150
    ]

})

df

    Area  Bedrooms  Age  Price
0    800         2   18     38
1    900         2   15     43
2    950         2   14     46
3   1000         2   13     50
4   1100         2   12     55
5   1200         3   11     61
6   1300         3   10     67
7   1400         3    9     73
8   1500         3    8     79
9   1600         3    8     84
10  1700         3    7     89
11  1800         3    6     95
12  1900         4    5    103
13  2000         4    5    110
14  2100         4    4    116
15  2200         4    4    122
16  2300         4    3    128
17  2400         4    3    134
18  2500         5    2    142
19  2600         5    1    150

In [ ]:
x = df[["Area", "Bedrooms", "Age"]]
y = df["Price"]

In [ ]:
x

    Area  Bedrooms  Age
0    800         2   18
1    900         2   15
2    950         2   14
3   1000         2   13
4   1100         2   12
5   1200         3   11
6   1300         3   10
7   1400         3    9
8   1500         3    8
9   1600         3    8
10  1700         3    7
11  1800         3    6
12  1900         4    5
13  2000         4    5
14  2100         4    4
15  2200         4    4
16  2300         4    3
17  2400         4    3
18  2500         5    2
19  2600         5    1

In [ ]:
y

0      38
1      43
2      46
3      50
4      55
5      61
6      67
7      73
8      79
9      84
10     89
11     95
12    103
13    110
14    116
15    122
16    128
17    134
18    142
19    150
Name: Price, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 42
)

In [ ]:
x_train

    Area  Bedrooms  Age
8   1500         3    8
5   1200         3   11
11  1800         3    6
3   1000         2   13
18  2500         5    2
16  2300         4    3
13  2000         4    5
2    950         2   14
9   1600         3    8
19  2600         5    1
4   1100         2   12
12  1900         4    5
7   1400         3    9
10  1700         3    7
14  2100         4    4
6   1300         3   10

In [ ]:
y_train

8      79
5      61
11     95
3      50
18    142
16    128
13    110
2      46
9      84
19    150
4      55
12    103
7      73
10     89
14    116
6      67
Name: Price, dtype: int64

In [ ]:
x_test

    Area  Bedrooms  Age
0    800         2   18
17  2400         4    3
15  2200         4    4
1    900         2   15

In [ ]:
y_test

0      38
17    134
15    122
1      43
Name: Price, dtype: int64

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(x_train, y_train) #training

LinearRegression()

In [ ]:
prediction = model.predict(x_test) #predicting

In [ ]:
print(prediction)

[ 42.82531293 135.13012517 122.73541029  44.92795549]

In [ ]:
# # y = mx + c
# m -> coefficient
# c -> intercept

In [ ]:
print(model.coef_)

[0.070163   2.30614743 1.63788595]

In [ ]:
print(model.intercept_)

-47.399332406098466

#Residuals

In [ ]:
# residuals = actual - prediction

#MAE --> Mean Absolute Error

In [ ]:
actual        predicted

100   95
120   118
80    85

In [ ]:
from sklearn.metrics import mean_absolute_error

actual = [100, 120, 80]
predicted = [95, 118, 85]

mae = mean_absolute_error(actual, predicted)
mae

4.0

#RMSE --> Root Mean Square error

In [ ]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(actual, predicted)
print(mse)

18.0

In [ ]:
import numpy as np
rmse = np.sqrt(mse)
print(rmse)

4.242640687119285

In [ ]:
# r2 score --> how well does the model explain the variation within the data

In [ ]:
from sklearn.metrics import r2_score

r2 = r2_score(actual, predicted)
print(r2)

0.9325

In [ ]:
# Interpretation:
# 1 --> perfect model
# 0.95 --> excellent model
# 0.85 --> very good
# 0.7 --> acceptable
# 0.3 --> poor model

#Regularization

In [ ]:
# #overfitting

# Student a --> learns concepts from the test questions

# Student b --> memorizes the test questions

In [ ]:
# Overfitting --> model performs excellent on training data but poor on test data

In [ ]:
# Regularization --> keep the model simple. Simple models usually generalizes better

In [ ]:
# Types:

# L1 Regularization --> Lasso

# L2 Regularization --> Ridge

In [ ]:
#Ridge Regression: the coefficients shrink to smaller values but nothing becomes zero
#Lasso Regression: the coefficients shrink to smaller values and can also become zero

y = mx + c
# m1*x1 + m2*x2 + m3*x3 + c

In [ ]:
Ridge                                 Lasso
- Shrinks coefficients                - shrinks as well as removes the features
- keeps every feature                  - can remove features
- better when every feature matters     - preffered when many features are irrelevant