<a href="https://colab.research.google.com/github/Glaze0/Assignment/blob/main/Workshop_6_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello Friends!")

Hello Friends!

#Dataset

#Scaling
Min-Max scaling for a large amount of data, value ranges from (0-1) used when calcualting mean and standard deviation is hard.

Formula: `x-min/max-min`.

and use z-score(standard scaling) when data is not that big.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Customer_ID":[101,102,103,104,105],
    "Gender":["Male","Female","Female","Male","Female"],
    "City":["Pune","Mumbai","Delhi","Pune","Mumbai"],
    "Age":[25,None,35,40,30],
    "Purchase_Amount":[1200,800,2500,1800,900],
    "MRP":[1500,1000,3000,2000,1000],
    "Joining_Date":[
        "2022-01-15",
        "2021-06-10",
        "2023-02-20",
        "2020-09-05",
        "2022-12-12"
    ],
    "Purchased":[1,0,1,1,0]
})

df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased
0,101,Male,Pune,25.0,1200,1500,2022-01-15,1
1,102,Female,Mumbai,NaN,800,1000,2021-06-10,0
2,103,Female,Delhi,35.0,2500,3000,2023-02-20,1
3,104,Male,Pune,40.0,1800,2000,2020-09-05,1
4,105,Female,Mumbai,30.0,900,1000,2022-12-12,0

In [ ]:
df.head()

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased
0,101,Male,Pune,25.0,1200,1500,2022-01-15,1
1,102,Female,Mumbai,NaN,800,1000,2021-06-10,0
2,103,Female,Delhi,35.0,2500,3000,2023-02-20,1
3,104,Male,Pune,40.0,1800,2000,2020-09-05,1
4,105,Female,Mumbai,30.0,900,1000,2022-12-12,0

In [ ]:
df.head(2)

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased
0,101,Male,Pune,25.0,1200,1500,2022-01-15,1
1,102,Female,Mumbai,NaN,800,1000,2021-06-10,0

In [ ]:
df.tail()

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased
0,101,Male,Pune,25.0,1200,1500,2022-01-15,1
1,102,Female,Mumbai,NaN,800,1000,2021-06-10,0
2,103,Female,Delhi,35.0,2500,3000,2023-02-20,1
3,104,Male,Pune,40.0,1800,2000,2020-09-05,1
4,105,Female,Mumbai,30.0,900,1000,2022-12-12,0

In [ ]:
df.tail(2)

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased
3,104,Male,Pune,40.0,1800,2000,2020-09-05,1
4,105,Female,Mumbai,30.0,900,1000,2022-12-12,0

In [ ]:
df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased
0,101,Male,Pune,25.0,1200,1500,2022-01-15,1
1,102,Female,Mumbai,NaN,800,1000,2021-06-10,0
2,103,Female,Delhi,35.0,2500,3000,2023-02-20,1
3,104,Male,Pune,40.0,1800,2000,2020-09-05,1
4,105,Female,Mumbai,30.0,900,1000,2022-12-12,0

In [ ]:
df.shape

(5, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      5 non-null      int64
 1   Gender           5 non-null      object
 2   City             5 non-null      object
 3   Age              4 non-null      float64
 4   Purchase_Amount  5 non-null      int64
 5   MRP              5 non-null      int64
 6   Joining_Date     5 non-null      object
 7   Purchased        5 non-null      int64
dtypes: float64(1), int64(4), object(3)
memory usage: 452.0+ bytes

In [ ]:
df.describe()

       Customer_ID        Age  Purchase_Amount          MRP  Purchased
count     5.000000   4.000000         5.000000     5.000000   5.000000
mean    103.000000  32.500000      1440.000000  1700.000000   0.600000
std       1.581139   6.454972       709.224929   836.660027   0.547723
min     101.000000  25.000000       800.000000  1000.000000   0.000000
25%     102.000000  28.750000       900.000000  1000.000000   0.000000
50%     103.000000  32.500000      1200.000000  1500.000000   1.000000
75%     104.000000  36.250000      1800.000000  2000.000000   1.000000
max     105.000000  40.000000      2500.000000  3000.000000   1.000000

In [ ]:
df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased
0,101,Male,Pune,25.0,1200,1500,2022-01-15,1
1,102,Female,Mumbai,NaN,800,1000,2021-06-10,0
2,103,Female,Delhi,35.0,2500,3000,2023-02-20,1
3,104,Male,Pune,40.0,1800,2000,2020-09-05,1
4,105,Female,Mumbai,30.0,900,1000,2022-12-12,0

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["Gender"] = encoder.fit_transform(df["Gender"])

df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased
0,101,1,Pune,25.0,1200,1500,2022-01-15,1
1,102,0,Mumbai,NaN,800,1000,2021-06-10,0
2,103,0,Delhi,35.0,2500,3000,2023-02-20,1
3,104,1,Pune,40.0,1800,2000,2020-09-05,1
4,105,0,Mumbai,30.0,900,1000,2022-12-12,0

#Filling Missing data

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased
0,101,1,Pune,25.0,1200,1500,2022-01-15,1
1,102,0,Mumbai,32.5,800,1000,2021-06-10,0
2,103,0,Delhi,35.0,2500,3000,2023-02-20,1
3,104,1,Pune,40.0,1800,2000,2020-09-05,1
4,105,0,Mumbai,30.0,900,1000,2022-12-12,0

#Scaling

In [ ]:
# 1. Min Max Scaling --> Normalization

# x --> (x-min)/(max - min)

from sklearn.preprocessing import MinMaxScaler

mn_mx_sc = MinMaxScaler()

df["Age_scaled"] = mn_mx_sc.fit_transform(df[["Age"]])
df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased,Age_scaled
0,101,1,Pune,25.0,1200,1500,2022-01-15,1,0.000000
1,102,0,Mumbai,32.5,800,1000,2021-06-10,0,0.500000
2,103,0,Delhi,35.0,2500,3000,2023-02-20,1,0.666667
3,104,1,Pune,40.0,1800,2000,2020-09-05,1,1.000000
4,105,0,Mumbai,30.0,900,1000,2022-12-12,0,0.333333

In [ ]:
#2. Standardization --> Standard Scaler --> mean is close to 0 and std is close to 1

In [ ]:
from sklearn.preprocessing import StandardScaler

std_sc = StandardScaler()

df["MRP_scaled"] = std_sc.fit_transform(df[["MRP"]])
df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased,Age_scaled,MRP_scaled
0,101,1,Pune,25.0,1200,1500,2022-01-15,1,0.000000,-0.267261
1,102,0,Mumbai,32.5,800,1000,2021-06-10,0,0.500000,-0.935414
2,103,0,Delhi,35.0,2500,3000,2023-02-20,1,0.666667,1.737198
3,104,1,Pune,40.0,1800,2000,2020-09-05,1,1.000000,0.400892
4,105,0,Mumbai,30.0,900,1000,2022-12-12,0,0.333333,-0.935414

In [ ]:
df.describe()

,Customer_ID,Gender,Age,Purchase_Amount,MRP,Purchased,Age_scaled,MRP_scaled
count,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000e+00
mean,103.000000,0.400000,32.50000,1440.000000,1700.000000,0.600000,0.500000,2.220446e-17
std,1.581139,0.547723,5.59017,709.224929,836.660027,0.547723,0.372678,1.118034e+00
min,101.000000,0.000000,25.00000,800.000000,1000.000000,0.000000,0.000000,-9.354143e-01
25%,102.000000,0.000000,30.00000,900.000000,1000.000000,0.000000,0.333333,-9.354143e-01
50%,103.000000,0.000000,32.50000,1200.000000,1500.000000,1.000000,0.500000,-2.672612e-01
75%,104.000000,1.000000,35.00000,1800.000000,2000.000000,1.000000,0.666667,4.008919e-01
max,105.000000,1.000000,40.00000,2500.000000,3000.000000,1.000000,1.000000,1.737198e+00

#Feature Engineering

In [ ]:
df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased,Age_scaled,MRP_scaled
0,101,1,Pune,25.0,1200,1500,2022-01-15,1,0.000000,-0.267261
1,102,0,Mumbai,32.5,800,1000,2021-06-10,0,0.500000,-0.935414
2,103,0,Delhi,35.0,2500,3000,2023-02-20,1,0.666667,1.737198
3,104,1,Pune,40.0,1800,2000,2020-09-05,1,1.000000,0.400892
4,105,0,Mumbai,30.0,900,1000,2022-12-12,0,0.333333,-0.935414

In [ ]:
df["Discount"]  = df["MRP"] - df["Purchase_Amount"]
df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased,Age_scaled,MRP_scaled,Discount
0,101,1,Pune,25.0,1200,1500,2022-01-15,1,0.000000,-0.267261,300
1,102,0,Mumbai,32.5,800,1000,2021-06-10,0,0.500000,-0.935414,200
2,103,0,Delhi,35.0,2500,3000,2023-02-20,1,0.666667,1.737198,500
3,104,1,Pune,40.0,1800,2000,2020-09-05,1,1.000000,0.400892,200
4,105,0,Mumbai,30.0,900,1000,2022-12-12,0,0.333333,-0.935414,100

In [ ]:
df["Discount_percentage"] = df["Discount"]*100/df["MRP"]

In [ ]:
df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased,Age_scaled,MRP_scaled,Discount,Discount_percentage
0,101,1,Pune,25.0,1200,1500,2022-01-15,1,0.000000,-0.267261,300,20.000000
1,102,0,Mumbai,32.5,800,1000,2021-06-10,0,0.500000,-0.935414,200,20.000000
2,103,0,Delhi,35.0,2500,3000,2023-02-20,1,0.666667,1.737198,500,16.666667
3,104,1,Pune,40.0,1800,2000,2020-09-05,1,1.000000,0.400892,200,10.000000
4,105,0,Mumbai,30.0,900,1000,2022-12-12,0,0.333333,-0.935414,100,10.000000

In [ ]:
#Since how mnay days the customer is on our platform?

df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])
df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased,Age_scaled,MRP_scaled,Discount,Discount_percentage
0,101,1,Pune,25.0,1200,1500,2022-01-15,1,0.000000,-0.267261,300,20.000000
1,102,0,Mumbai,32.5,800,1000,2021-06-10,0,0.500000,-0.935414,200,20.000000
2,103,0,Delhi,35.0,2500,3000,2023-02-20,1,0.666667,1.737198,500,16.666667
3,104,1,Pune,40.0,1800,2000,2020-09-05,1,1.000000,0.400892,200,10.000000
4,105,0,Mumbai,30.0,900,1000,2022-12-12,0,0.333333,-0.935414,100,10.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Customer_ID          5 non-null      int64
 1   Gender               5 non-null      int64
 2   City                 5 non-null      object
 3   Age                  5 non-null      float64
 4   Purchase_Amount      5 non-null      int64
 5   MRP                  5 non-null      int64
 6   Joining_Date         5 non-null      datetime64[ns]
 7   Purchased            5 non-null      int64
 8   Age_scaled           5 non-null      float64
 9   MRP_scaled           5 non-null      float64
 10  Discount             5 non-null      int64
 11  Discount_percentage  5 non-null      float64
dtypes: datetime64[ns](1), float64(4), int64(6), object(1)
memory usage: 612.0+ bytes

In [ ]:
today = pd.Timestamp("2026-06-28")

In [ ]:
today

Timestamp('2026-06-28 00:00:00')

In [ ]:
df["Active_Days"] = (today-df["Joining_Date"])

In [ ]:
df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased,Age_scaled,MRP_scaled,Discount,Discount_percentage,Active_Days
0,101,1,Pune,25.0,1200,1500,2022-01-15,1,0.000000,-0.267261,300,20.000000,1625 days
1,102,0,Mumbai,32.5,800,1000,2021-06-10,0,0.500000,-0.935414,200,20.000000,1844 days
2,103,0,Delhi,35.0,2500,3000,2023-02-20,1,0.666667,1.737198,500,16.666667,1224 days
3,104,1,Pune,40.0,1800,2000,2020-09-05,1,1.000000,0.400892,200,10.000000,2122 days
4,105,0,Mumbai,30.0,900,1000,2022-12-12,0,0.333333,-0.935414,100,10.000000,1294 days

In [ ]:
df["Active_Days"] = (today-df["Joining_Date"]).dt.days

In [ ]:
df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased,Age_scaled,MRP_scaled,Discount,Discount_percentage,Active_Days
0,101,1,Pune,25.0,1200,1500,2022-01-15,1,0.000000,-0.267261,300,20.000000,1625
1,102,0,Mumbai,32.5,800,1000,2021-06-10,0,0.500000,-0.935414,200,20.000000,1844
2,103,0,Delhi,35.0,2500,3000,2023-02-20,1,0.666667,1.737198,500,16.666667,1224
3,104,1,Pune,40.0,1800,2000,2020-09-05,1,1.000000,0.400892,200,10.000000,2122
4,105,0,Mumbai,30.0,900,1000,2022-12-12,0,0.333333,-0.935414,100,10.000000,1294

In [ ]:
df["Age_Group"] = pd.cut(df["Age"],
                         bins = [0,25,38,60],
                         labels = ["Young" , "Adult", "Senior"]
                         )
df

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Purchased,Age_scaled,MRP_scaled,Discount,Discount_percentage,Active_Days,Age_Group
0,101,1,Pune,25.0,1200,1500,2022-01-15,1,0.000000,-0.267261,300,20.000000,1625,Young
1,102,0,Mumbai,32.5,800,1000,2021-06-10,0,0.500000,-0.935414,200,20.000000,1844,Adult
2,103,0,Delhi,35.0,2500,3000,2023-02-20,1,0.666667,1.737198,500,16.666667,1224,Adult
3,104,1,Pune,40.0,1800,2000,2020-09-05,1,1.000000,0.400892,200,10.000000,2122,Senior
4,105,0,Mumbai,30.0,900,1000,2022-12-12,0,0.333333,-0.935414,100,10.000000,1294,Adult

In [ ]:
# x --> features
# y --> target

In [ ]:
df1 = df[["Customer_ID", "Gender"]]
df1

   Customer_ID  Gender
0          101       1
1          102       0
2          103       0
3          104       1
4          105       0

In [ ]:
x = df.drop(["Purchased"], axis = 1)
y = df["Purchased"]


x

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Age_scaled,MRP_scaled,Discount,Discount_percentage,Active_Days,Age_Group
0,101,1,Pune,25.0,1200,1500,2022-01-15,0.000000,-0.267261,300,20.000000,1625,Young
1,102,0,Mumbai,32.5,800,1000,2021-06-10,0.500000,-0.935414,200,20.000000,1844,Adult
2,103,0,Delhi,35.0,2500,3000,2023-02-20,0.666667,1.737198,500,16.666667,1224,Adult
3,104,1,Pune,40.0,1800,2000,2020-09-05,1.000000,0.400892,200,10.000000,2122,Senior
4,105,0,Mumbai,30.0,900,1000,2022-12-12,0.333333,-0.935414,100,10.000000,1294,Adult

In [ ]:
y

0    1
1    0
2    1
3    1
4    0
Name: Purchased, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [ ]:
x_train

,Customer_ID,Gender,City,Age,Purchase_Amount,MRP,Joining_Date,Age_scaled,MRP_scaled,Discount,Discount_percentage,Active_Days,Age_Group
4,105,0,Mumbai,30.0,900,1000,2022-12-12,0.333333,-0.935414,100,10.000000,1294,Adult
2,103,0,Delhi,35.0,2500,3000,2023-02-20,0.666667,1.737198,500,16.666667,1224,Adult
0,101,1,Pune,25.0,1200,1500,2022-01-15,0.000000,-0.267261,300,20.000000,1625,Young
3,104,1,Pune,40.0,1800,2000,2020-09-05,1.000000,0.400892,200,10.000000,2122,Senior